Feature/cloudinary
DmytroKolisnyk2/audioCatalogAPI pull request #12
Opened 2022-10-12 12:34 UTC by MaxPopsuy

2022-10-13 16:16 UTC, Igoryakib approved these changes

2022-10-13 16:23 UTC, Igoryakib requested changes
Фу нельзя таку каку мерджить

2022-10-13 16:28 UTC, Igoryakib approved these changes

2022-10-13 16:28 UTC, Igoryakib requested changes
Діма перевір цю каку перед мерджом

2022-10-14 03:41 UTC, DmytroKolisnyk2 approved these changes

2022-10-14 03:41 UTC, DmytroKolisnyk2 commented on src/utils/multer-config.ts
> +  ) {
винеси в єнам з дозволеними розширеннями

2022-10-14 03:41 UTC, DmytroKolisnyk2 commented on src/utils/multer-config.ts
> +  ) {
так само

2022-10-14 16:33 UTC, DmytroKolisnyk2 approved these changes

2022-10-14 16:34 UTC, DmytroKolisnyk2 requested changes
онови поля в example.env

2022-10-14 17:24 UTC, merged