Feature/authorization
DmytroKolisnyk2/audioCatalogAPI pull request #13
Opened 2022-10-12 17:34 UTC by Igoryakib

2022-10-13 16:24 UTC, MaxPopsuy requested changes, later dismissed
фу 878 змін в package.lock.json, нізя так

2022-10-13 16:24 UTC, Igoryakib reviewed
Діма Давай швидше

2022-10-13 16:25 UTC, MaxPopsuy commented
> Діма Давай швидше

легенда

2022-10-14 03:47 UTC, DmytroKolisnyk2 approved these changes

2022-10-14 03:47 UTC, DmytroKolisnyk2 commented on src/utils/jwtToken.ts
> +};
давай в константу

2022-10-14 17:55 UTC, merged